# Generated by Django 3.0.4 on 2020-04-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_title', models.CharField(max_length=200, verbose_name='Название ')),
                ('description_text', models.TextField(verbose_name='Текст информации')),
            ],
            options={
                'verbose_name': 'Описание',
                'verbose_name_plural': 'Описание',
            },
        ),
        migrations.CreateModel(
            name='inform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inform_title', models.CharField(max_length=200, verbose_name='Название ')),
                ('inform_text', models.TextField(null=True, verbose_name='Текст информации')),
                ('inform_file', models.FileField(null=True, upload_to='uploads/', verbose_name='файл')),
            ],
            options={
                'verbose_name': 'Информация для поциента',
                'verbose_name_plural': 'Информация для поциентов',
            },
        ),
    ]
