# Generated by Django 3.0.4 on 2020-04-30 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='inform',
            new_name='informeit',
        ),
        migrations.AlterModelOptions(
            name='description',
            options={'verbose_name': 'Описание', 'verbose_name_plural': ('Описание',)},
        ),
        migrations.RenameField(
            model_name='informeit',
            old_name='inform_file',
            new_name='informeit_file',
        ),
        migrations.RenameField(
            model_name='informeit',
            old_name='inform_text',
            new_name='informeit_text',
        ),
        migrations.RenameField(
            model_name='informeit',
            old_name='inform_title',
            new_name='informeit_title',
        ),
    ]
