# Generated by Django 3.0.4 on 2020-05-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dop_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dop_info_title', models.CharField(max_length=200, verbose_name='Название ')),
                ('dop_info_text', models.TextField(verbose_name='текст')),
                ('dop_info_image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('dop_info_files', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='файл')),
            ],
            options={
                'verbose_name': 'Дополнительная информация',
                'verbose_name_plural': 'Дополнительная информация',
            },
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(verbose_name='текст сообщения')),
                ('message_name', models.CharField(max_length=200, verbose_name='Имя отправителя ')),
                ('message_phone', models.CharField(max_length=20, verbose_name='телефон ')),
                ('massage_email', models.EmailField(max_length=50, verbose_name='mail')),
            ],
            options={
                'verbose_name': 'Сообщения пользователя',
                'verbose_name_plural': 'Сообщение пользователей',
            },
        ),
        migrations.CreateModel(
            name='units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_name', models.TextField(verbose_name='Подразделение')),
                ('units_adres', models.TextField(verbose_name='адрес')),
                ('units_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('units_index', models.CharField(max_length=6, verbose_name='Индекс')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
    ]
