# Generated by Django 3.0.4 on 2020-05-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_email', models.EmailField(max_length=254, verbose_name='Email ')),
                ('c_neme', models.CharField(max_length=100, verbose_name='Имя')),
                ('c_text', models.TextField(max_length=5000, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'каментарии ',
                'verbose_name_plural': 'каментарии',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email ')),
                ('neme', models.CharField(max_length=100, verbose_name='Имя')),
                ('text', models.TextField(max_length=5000, verbose_name='Сообщение')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Контактная форма ',
                'verbose_name_plural': 'Контактная форма',
            },
        ),
    ]
