# Generated by Django 3.0.4 on 2020-05-12 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_comment_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='text',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='neme',
            new_name='name',
        ),
    ]
