# Generated by Django 3.0.4 on 2020-05-12 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20200513_0053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Comment',
        ),
    ]
