# Generated by Django 3.0.4 on 2020-04-30 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Histori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managing_image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('histori_name', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('histori_text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'История диспансера',
                'verbose_name_plural': 'История диспансера',
            },
        ),
        migrations.CreateModel(
            name='coment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coment_name', models.CharField(max_length=200, verbose_name='имя автора')),
                ('coment_text', models.TextField(verbose_name='Текст')),
                ('histori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='histori.Histori')),
            ],
            options={
                'verbose_name': 'коментарий',
                'verbose_name_plural': 'Коментарии',
            },
        ),
    ]
