# Generated by Django 3.0.4 on 2020-05-11 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('histori', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coment',
            name='histori',
        ),
        migrations.RemoveField(
            model_name='histori',
            name='managing_image',
        ),
    ]
