# Generated by Django 3.0.4 on 2020-04-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='managing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managing_fio', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('managing_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('managing_middle', models.CharField(max_length=40, null=True, verbose_name='Отчество')),
                ('managing_position', models.TextField(verbose_name='Должность')),
                ('managing_phone', models.TextField(verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Описание',
                'verbose_name_plural': 'Описание',
            },
        ),
        migrations.CreateModel(
            name='staff_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staf_file_title', models.CharField(max_length=200, verbose_name='Название ')),
                ('staff_file_files', models.FileField(null=True, upload_to='uploads/', verbose_name='файл')),
            ],
            options={
                'verbose_name': 'Мед работники файл',
                'verbose_name_plural': 'Мед работники файлы',
            },
        ),
    ]
