# Generated by Django 3.0.4 on 2020-04-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managing',
            options={'verbose_name': 'Управляющий персонал', 'verbose_name_plural': 'Управляющий персонал'},
        ),
        migrations.AddField(
            model_name='managing',
            name='managing_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
    ]
