# Generated by Django 3.0.4 on 2020-05-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200430_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='med',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_name', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('med_text', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Описание мед работкик',
                'verbose_name_plural': 'Описание мед работкики',
            },
        ),
    ]
