# Generated by Django 3.0.4 on 2020-05-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_med'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_file',
            name='staff_file_files',
            field=models.FileField(null=True, upload_to='user_media', verbose_name='файл'),
        ),
    ]
