# Generated by Django 3.0.4 on 2020-05-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0003_auto_20200514_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug_file',
            name='drug_file_files',
            field=models.FileField(null=True, upload_to='uploads/', verbose_name='файл'),
        ),
    ]
