# Generated by Django 3.0.4 on 2020-04-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=20, verbose_name='Заголовок')),
                ('document_list', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Описание',
                'verbose_name_plural': 'Описание',
            },
        ),
        migrations.CreateModel(
            name='document_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file_title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('document_file_files', models.FileField(null=True, upload_to='uploads/', verbose_name='файл')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
