# Generated by Django 3.0.4 on 2020-05-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0003_remove_main_text_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.AlterField(
            model_name='imageng',
            name='imageng_nav',
            field=models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
