# Generated by Django 3.0.4 on 2020-05-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0004_auto_20200509_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=60)),
                ('description', models.TextField(blank=True, default='', max_length=200)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('image', models.ImageField(height_field='height', upload_to='', width_field='width')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Photo',
                'ordering': ['timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='imageng',
        ),
    ]
