# Generated by Django 3.0.4 on 2020-05-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0006_auto_20200513_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
