# Generated by Django 3.0.4 on 2020-05-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.TextField(verbose_name='Организация')),
                ('unit_adres', models.TextField(verbose_name='адрес')),
                ('unit_phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Организации',
                'verbose_name_plural': 'Организация',
            },
        ),
        migrations.CreateModel(
            name='up_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_file_title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('upt_file_files', models.FileField(null=True, upload_to='user_media', verbose_name='файл')),
            ],
        ),
        migrations.CreateModel(
            name='uporg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uporg_title', models.CharField(max_length=20, verbose_name='Заголовок')),
                ('uporg_list', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Описание',
                'verbose_name_plural': 'Описание',
            },
        ),
    ]
