# Generated by Django 3.0.4 on 2020-04-30 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='grupp_healthy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupp_healthy_name', models.CharField(max_length=200, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Заголовок группы',
                'verbose_name_plural': 'Заголовок группы',
            },
        ),
        migrations.CreateModel(
            name='healthy_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospis_file_title', models.CharField(max_length=200, verbose_name='Заголовок ')),
                ('hospis_file_files', models.FileField(null=True, upload_to='uploads/', verbose_name='файл')),
                ('healthy_file_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthy.grupp_healthy')),
            ],
            options={
                'verbose_name': 'Файл группы',
                'verbose_name_plural': 'Файлы группы',
            },
        ),
    ]
